#!/usr/bin/env python3
"""Generate SQL from photo_manifest.csv + processed images.

Builds an index of processed files by stripping category prefix and
sequence suffix to recover the original stem, then joins against the manifest.
"""

import csv
import os
import sys
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MANIFEST = os.path.join(SCRIPT_DIR, "photo_manifest.csv")
PROCESSED_DIR = os.path.join(SCRIPT_DIR, "processed")
SQL_FILE = os.path.join(SCRIPT_DIR, "sql", "batch_insert.sql")


def sql_quote(s):
    return "'" + str(s).replace("'", "''") + "'"


def main():
    if not os.path.isfile(MANIFEST):
        print(f"ERROR: Manifest not found: {MANIFEST}", file=sys.stderr)
        sys.exit(1)

    # ── Step 1: Build index of all processed files ──
    # Processed names: "panel-upgrade-20170619_083316-01.jpg"
    # Original names:  "20170619_083316.jpg"
    # Strategy: strip category prefix, strip trailing -NN, get original stem.
    processed_index = defaultdict(dict)  # category → { orig_stem_lower → proc_filename }

    for cat_name in sorted(os.listdir(PROCESSED_DIR)):
        cat_dir = os.path.join(PROCESSED_DIR, cat_name)
        if not os.path.isdir(cat_dir):
            continue
        for proc_file in os.listdir(cat_dir):
            if not proc_file.lower().endswith((".jpg", ".jpeg", ".png")):
                continue
            # Remove extension
            base = proc_file.rsplit(".", 1)[0]  # "panel-upgrade-20170619_083316-01"
            # Strip category prefix + hyphen: len("panel-upgrade") = 12, +1 for hyphen
            prefix = cat_name + "-"
            if base.startswith(prefix):
                rest = base[len(prefix):]  # "20170619_083316-01"
            else:
                rest = base
            # Strip trailing sequence number: "20170619_083316-01" → "20170619_083316"
            last_dash = rest.rfind("-")
            if last_dash > 0:
                orig_stem = rest[:last_dash]
            else:
                orig_stem = rest
            processed_index[cat_name][orig_stem.lower()] = proc_file

    total_indexed = sum(len(v) for v in processed_index.values())
    print(f"Indexed {total_indexed} processed files across {len(processed_index)} categories")

    # ── Step 2: Generate SQL from manifest ──
    os.makedirs(os.path.dirname(SQL_FILE), exist_ok=True)

    total = 0
    matched = 0
    unmatched = 0
    categories = {}

    with open(MANIFEST, newline="") as manifest, open(SQL_FILE, "w") as sql:
        sql.write("""-- AMY Electric Gallery — Batch Insert
-- Generated by generate_sql.py from photo_manifest.csv
-- Run: npx wrangler d1 execute amyelectric_db --remote --file=batch_insert.sql

BEGIN TRANSACTION;

""")
        reader = csv.DictReader(manifest)

        for row in reader:
            total += 1
            fname = row["filename"]
            category = row["category"]
            description = row["description"]
            location = row["location"]
            date = row.get("date", "")

            categories[category] = categories.get(category, 0) + 1

            # Look up processed file
            orig_stem = os.path.splitext(fname)[0].lower()
            proc_file = processed_index.get(category, {}).get(orig_stem)

            if proc_file is None:
                unmatched += 1
                if unmatched <= 5:
                    print(f"  UNMATCHED: {fname} (stem={orig_stem}, cat={category})")
                continue

            safe_filename = sql_quote(proc_file)
            safe_category = sql_quote(category)
            safe_desc = sql_quote(description)
            safe_location = sql_quote(location)
            safe_date = sql_quote(date) if date else "NULL"

            sql.write(
                f"INSERT INTO gallery_images (filename, category, title, description, location, width, height, shoot_date, created_at)\n"
                f"VALUES ({safe_filename}, {safe_category}, {safe_desc}, {safe_desc}, {safe_location}, 0, 0, {safe_date}, datetime('now'));\n"
            )
            matched += 1

            if matched % 500 == 0:
                print(f"  {matched} SQL rows written...")

        sql.write("\nCOMMIT;\n")

    print(f"\nDone:")
    print(f"  Manifest entries: {total}")
    print(f"  Matched (SQL rows): {matched}")
    print(f"  Unmatched: {unmatched}")
    print(f"  SQL: {SQL_FILE}")
    print(f"\nBy category:")
    for cat in sorted(categories, key=categories.get, reverse=True):
        print(f"  {cat}: {categories[cat]}")


if __name__ == "__main__":
    main()
